<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageVersion>0.1.0</PackageVersion>
    <Authors>Henrik Cooke</Authors>
    <Description>Statically type scripting language for embedding.</Description>
    <Copyright>Henrik Cooke</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNext.Metaprogramming" Version="4.7.5" />
  </ItemGroup>

</Project>
